# Generated by Django 4.1.6 on 2023-02-04 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

#

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mainApp", "0001_initial"),
        ("countries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cargoes",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes_recipient",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Получатель",
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="recipient_city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes_recipient",
                to="countries.cities",
                verbose_name="Город получателя",
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="recipient_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes_recipient",
                to="countries.countries",
                verbose_name="Страна получателя",
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes_send",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="sender_city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes_sender",
                to="countries.cities",
                verbose_name="Город получателя",
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="sender_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes_send",
                to="countries.countries",
                verbose_name="Страна отправителя",
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="shipping_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainApp.shipment",
                verbose_name="Способ отправки",
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainApp.status",
                verbose_name="Статус",
            ),
        ),
    ]
