# Generated by Django 4.1.6 on 2023-02-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cargoes",
            options={"verbose_name": "Грузы", "verbose_name_plural": "Грузы"},
        ),
        migrations.AlterModelOptions(
            name="events",
            options={"verbose_name": "События", "verbose_name_plural": "События"},
        ),
        migrations.AlterModelOptions(
            name="paystatus",
            options={
                "verbose_name": "Статусы оплаты",
                "verbose_name_plural": "Статусы оплаты",
            },
        ),
        migrations.AlterModelOptions(
            name="paytype",
            options={
                "verbose_name": "Способы оплаты",
                "verbose_name_plural": "Способы оплаты",
            },
        ),
        migrations.AlterModelOptions(
            name="shipment",
            options={
                "verbose_name": "Способы отгрузки",
                "verbose_name_plural": "Способы отгрузки",
            },
        ),
        migrations.AlterModelOptions(
            name="status",
            options={
                "verbose_name": "Статусы доставки",
                "verbose_name_plural": "Статусы доставки",
            },
        ),
        migrations.RemoveField(model_name="cargoes", name="shipment",),
        migrations.AddField(
            model_name="cargoes",
            name="name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название груза"
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="slug",
            field=models.SlugField(
                max_length=255, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
