# Generated by Django 4.1.6 on 2023-05-04 07:17

from django.db import migrations, models
import django.db.models.deletion

#


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0004_alter_cities_options_alter_countries_options"),
        ("mainApp", "0003_alter_cargoes_options_alter_events_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoes",
            name="bar_code",
            field=models.ImageField(
                blank=True, upload_to="mainApp/images/bar_code", verbose_name="BAR"
            ),
        ),
        migrations.AlterField(
            model_name="cargoes",
            name="date_create",
            field=models.DateTimeField(
                blank=True, verbose_name="Дата и время создания"
            ),
        ),
        migrations.AlterField(
            model_name="cargoes",
            name="qr_code",
            field=models.ImageField(
                blank=True, upload_to="mainApp/images/qr_code", verbose_name="QR"
            ),
        ),
        migrations.AlterField(
            model_name="cargoes",
            name="sender_city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes_sender",
                to="countries.cities",
                verbose_name="Город отправителя",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="mainApp.cargoes",
            ),
        ),
    ]
