# Generated by Django 4.1.6 on 2023-05-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0004_alter_cargoes_bar_code_alter_cargoes_date_create_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cargoes", name="recipient",),
        migrations.RemoveField(model_name="cargoes", name="sender",),
        migrations.AddField(
            model_name="cargoes",
            name="recipient_email",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ФИО отправителя"
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="recipient_fullname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ФИО отправителя"
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="recipient_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер отправителя"
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="sender_email",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ФИО отправителя"
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="sender_fullname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ФИО отправителя"
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="sender_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер отправителя"
            ),
        ),
    ]
