# Generated by Django 4.1.6 on 2023-05-19 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0005_remove_cargoes_recipient_remove_cargoes_sender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип принятия",
                "verbose_name_plural": "Тип принятия",
            },
        ),
        migrations.CreateModel(
            name="WorkStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Статусы работы",
                "verbose_name_plural": "Статусы работы",
            },
        ),
        migrations.AddField(
            model_name="cargoes",
            name="accept_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes",
                to="mainApp.accepttype",
                verbose_name="Тип выдачи",
            ),
        ),
        migrations.AddField(
            model_name="cargoes",
            name="work_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes",
                to="mainApp.workstatus",
                verbose_name="Статус обработки",
            ),
        ),
    ]
