# Generated by Django 4.1.6 on 2023-06-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_accepttype_workstatus_cargoes_accept_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoes",
            name="customs_clearance",
            field=models.PositiveIntegerField(default=0, verbose_name="Растаможка"),
        ),
        migrations.AlterField(
            model_name="cargoes",
            name="extra_expenses",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Дополнительные расходы"
            ),
        ),
        migrations.AlterField(
            model_name="cargoes",
            name="pay_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainApp.paystatus",
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="cargoes",
            name="pay_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainApp.paytype",
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="cargoes",
            name="recipient_email",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Email получателя"
            ),
        ),
        migrations.AlterField(
            model_name="cargoes",
            name="recipient_fullname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ФИО получателя"
            ),
        ),
        migrations.AlterField(
            model_name="cargoes",
            name="recipient_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер получателя"
            ),
        ),
        migrations.AlterField(
            model_name="cargoes",
            name="sender_email",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Email отправителя"
            ),
        ),
    ]
