# Generated by Django 4.1.6 on 2023-06-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0007_alter_cargoes_customs_clearance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoes",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата оплаты"),
        ),
    ]
