# Generated by Django 4.1.6 on 2023-02-14 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0002_countries_code_countries_initials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cities",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="countries.countries",
                verbose_name="Страна",
            ),
        ),
    ]
