# Generated by Django 4.1.6 on 2023-02-04 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
#


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("countries", "0001_initial"),
        ("felials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="felials",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="felials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="extraadresfelials",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="countries.cities",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="extraadresfelials",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="countries.countries",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="extraadresfelials",
            name="felial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_adres",
                to="felials.felials",
                verbose_name="Фелиал",
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="felial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crew",
                to="felials.felials",
                verbose_name="Фелиал",
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_in",
                to="felials.positions",
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
