# Generated by Django 4.1.6 on 2023-05-04 07:17

from django.db import migrations, models
#


class Migration(migrations.Migration):

    dependencies = [
        ("felials", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={"verbose_name": "Сотрудники", "verbose_name_plural": "Сотрудники"},
        ),
        migrations.AlterModelOptions(
            name="extraadresfelials",
            options={
                "verbose_name": "Дополнительные адреса",
                "verbose_name_plural": "Дополнительные адреса",
            },
        ),
        migrations.AlterModelOptions(
            name="felials",
            options={"verbose_name": "Филиалы", "verbose_name_plural": "Филиалы"},
        ),
        migrations.AlterModelOptions(
            name="positions",
            options={"verbose_name": "Должности", "verbose_name_plural": "Должности"},
        ),
        migrations.AlterField(
            model_name="felials",
            name="image",
            field=models.ImageField(
                blank=True,
                default="felials/image/no-image.jpg",
                upload_to="felials/image",
                verbose_name="Лого",
            ),
        ),
    ]
