# Generated by Django 4.1.6 on 2023-02-04 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

#


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email адресс"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Фамилия"
                    ),
                ),
                (
                    "adres",
                    models.CharField(blank=True, max_length=512, verbose_name="Адрес"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        upload_to="user/images/qr_code", verbose_name="QR"
                    ),
                ),
                (
                    "manager",
                    models.BooleanField(default=False, verbose_name="Мэнеджер"),
                ),
                (
                    "delivery",
                    models.BooleanField(
                        default=False, verbose_name="Ответственный за доставку"
                    ),
                ),
                ("partner", models.BooleanField(default=False, verbose_name="Партнер")),
                ("staff", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
                (
                    "date_of_register",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 2, 4, 16, 43, 38, 127035),
                        null=True,
                        verbose_name="Дата регистрации",
                    ),
                ),
                (
                    "last_visit",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 2, 4, 16, 43, 38, 127035),
                        verbose_name="Последняя активность",
                    ),
                ),
                (
                    "login_count",
                    models.PositiveIntegerField(
                        blank=True, default=1, verbose_name="Количество входов на сайт"
                    ),
                ),
                (
                    "edit_count",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        verbose_name="Количество редактирований профиля",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries.cities",
                        verbose_name="Город",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries.countries",
                        verbose_name="Страна",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователей",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="ExtraAdresUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adres", models.CharField(max_length=512, verbose_name="Адрес")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries.cities",
                        verbose_name="Город",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries.countries",
                        verbose_name="Страна",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_adres",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
