# Generated by Django 4.1.6 on 2023-02-09 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_city_alter_user_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_register",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 2, 10, 1, 31, 21, 105837),
                null=True,
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_visit",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 2, 10, 1, 31, 21, 105837),
                verbose_name="Последняя активность",
            ),
        ),
    ]
