# Generated by Django 4.1.6 on 2023-02-15 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_date_of_register_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_register",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 2, 15, 11, 22, 11, 782035, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_visit",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 2, 15, 11, 22, 11, 838028, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Последняя активность",
            ),
        ),
    ]
