# Generated by Django 4.1.6 on 2023-05-19 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_date_of_register_alter_user_last_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_register",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 5, 19, 2, 50, 57, 283649, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_visit",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 5, 19, 2, 50, 57, 338655, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Последняя активность",
            ),
        ),
    ]
