# Generated by Django 4.1.6 on 2023-06-06 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_user_date_of_register_alter_user_last_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_register",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 6, 6, 14, 16, 9, 653360, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_visit",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 6, 6, 14, 16, 14, 258339, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Последняя активность",
            ),
        ),
    ]
